
[.columns]
== Generic Toolbox :: Coefficient Form PDEs 

===  Coefficient Form PDEs 

Many (mono/multi)physics problem can be written into a system of generic PDE, parametrized by some coefficients :

[.column]
--
[latexmath]
++++
\[d \frac{\partial u}{\partial t} + \nabla \cdot \left( -c \nabla u - \alpha u + \gamma \right) + \beta \cdot \nabla u + a u = f \quad \text{ in } \Omega\]
++++
--
[.column]
--
* latexmath:[$d$] : damping or mass coefficient
* latexmath:[$c$] : diffusion coefficient
* latexmath:[$\alpha$] : conservative flux convection coefficient
* latexmath:[$\gamma$] : conservative flux source term

* latexmath:[$\beta$] : convection coefficient
* latexmath:[$a$] : absorption or reaction coefficient
* latexmath:[$f$] : source term
--

[.columns]
=== Cahn Hilliard

[.column]
--
--
[.column.xx-small]
--
.Phase separation modeling
[stem]
++++
\begin{aligned}
&\frac{\partial u}{\partial t}-\nabla \cdot M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \quad \text { in } \Omega \text {, }\\
&M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \text { on } \partial \Omega,\\
&M \lambda \nabla u \cdot n&=0 \quad \text { on } \partial \Omega .
\end{aligned}
++++

.Mixed Form
[stem]
++++
\begin{array}{cc}
\frac{\partial c}{\partial t}-\nabla \cdot M \nabla \mu=&0 \quad \text { in } \Omega, \\
\mu-\frac{d f}{d c}+\lambda \nabla^{2} c&=0 & \text { in } \Omega .
\end{array}
++++
--

[.columns]
=== Cahn Hilliard

[.column]
--
.2D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
.3D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
--
[.column.xx-small]
--
.Phase separation modeling
[source,json]
----
json here
----
--


[.columns]
=== Supra conductor

[.column]
--
images here
--
[.column.xx-small]
--
.Model equations
[stem]
++++
\begin{aligned}
&\frac{\partial u}{\partial t}-\nabla \cdot M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \quad \text { in } \Omega \text {, }\\
&M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \text { on } \partial \Omega,\\
&M \lambda \nabla u \cdot n&=0 \quad \text { on } \partial \Omega .
\end{aligned}
++++

.Mixed Form
[stem]
++++
\begin{array}{cc}
\frac{\partial c}{\partial t}-\nabla \cdot M \nabla \mu=&0 \quad \text { in } \Omega, \\
\mu-\frac{d f}{d c}+\lambda \nabla^{2} c&=0 & \text { in } \Omega .
\end{array}
++++
--

[.columns]
=== Supra Conductor

[.column]
--
.2D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
.3D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
--
[.column.xx-small]
--
.Phase separation modeling
[source,json]
----
json here
----
--
