
[.columns]
== Generic Toolbox :: Coefficient Form PDEs 

===  Coefficient Form PDEs 

Many (mono/multi)physics problem can be written into a system of generic PDE, parametrized by some coefficients :

[.column.x-small]
--
Find stem:[u_i,i=1...,N]  such that
[latexmath]
++++
d_i \frac{\partial u_i}{\partial t} + \nabla_i \cdot \left( -c \nabla u_i - \alpha u_i + \gamma_i \right) + \beta_i \cdot \nabla u_i + a u_i = f \quad \text{ in } \Omega
++++
--
[.column]
--
* latexmath:[$d_i$] : damping or mass coefficient
* latexmath:[$c_i$] : diffusion coefficient
* latexmath:[$\alpha_i$] : conservative flux convection coefficient
* latexmath:[$\gamma_i$] : conservative flux source term

* latexmath:[$\beta_i$] : convection coefficient
* latexmath:[$a_i$] : absorption or reaction coefficient
* latexmath:[$f_i$] : source term

The coefficients can depend on the unknowns stem:[u_j,j=1 \ldots N].

--

[.columns]
=== Cahn Hilliard

[.column]
--
--
[.column.xx-small]
--
.Phase separation modeling
[stem]
++++
\begin{aligned}
&\frac{\partial u}{\partial t}-\nabla \cdot M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \quad \text { in } \Omega \text {, }\\
&M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \text { on } \partial \Omega,\\
&M \lambda \nabla u \cdot n&=0 \quad \text { on } \partial \Omega .
\end{aligned}
++++

.Mixed Form
[stem]
++++
\begin{array}{cc}
\frac{\partial c}{\partial t}-\nabla \cdot M \nabla \mu=&0 \quad \text { in } \Omega, \\
\mu-\frac{d f}{d c}+\lambda \nabla^{2} c&=0 & \text { in } \Omega .
\end{array}
++++
--

[.columns]
=== Cahn Hilliard

[.column]
--
.2D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
.3D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
--
[.column.xx-small]
--
.Phase separation modeling
[source,json]
----
json here
----
--


[.columns]
=== Supra conductor

[.column]
--
images here
--
[.column.xx-small]
--
.Model equations
[stem]
++++
\begin{aligned}
&\frac{\partial u}{\partial t}-\nabla \cdot M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \quad \text { in } \Omega \text {, }\\
&M\left(\nabla\left(\frac{d f}{d u}-\lambda \nabla^{2} u\right)\right)&=0 \text { on } \partial \Omega,\\
&M \lambda \nabla u \cdot n&=0 \quad \text { on } \partial \Omega .
\end{aligned}
++++

.Mixed Form
[stem]
++++
\begin{array}{cc}
\frac{\partial c}{\partial t}-\nabla \cdot M \nabla \mu=&0 \quad \text { in } \Omega, \\
\mu-\frac{d f}{d c}+\lambda \nabla^{2} c&=0 & \text { in } \Omega .
\end{array}
++++
--

[.columns]
=== Supra Conductor

[.column]
--
.2D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
.3D
video::ZNke5e7ElR4[youtube, opts="autoplay,loop,modest",height=300]
--
[.column.xx-small]
--
.Phase separation modeling
[source,json]
----
json here
----
--
