#!/bin/bash
#
# Inital Setup see:
#    https://asciidoctor.org/docs/asciidoctor-revealjs/

BUNDLE=${1:-bundle}
#SRCFILES=(ch1-poisson.adoc ch2-prog.adoc ch3-diffusion.adoc ch4-elasticite.adoc ch5-stokes.adoc index.adoc)
#for SRCFILE in "${SRCFILES[@]}"; do
for SRCFILE in *.adoc; do

echo "Rendering $SRCFILE"

$BUNDLE exec asciidoctor-revealjs -r asciidoctor-diagram  -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@3.9.2  $SRCFILE
#$BUNDLE exec asciidoctor-revealjs -r asciidoctor-diagram    $SRCFILE
#npx asciidoctor-revealjs -r asciidoctor-diagram  -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@4.1.2  $SRCFILE
base=`basename $SRCFILE .adoc`
#echo "Starting Webserver on :8000"
#python -m SimpleHTTPServer >/dev/null 2>&1 & 

#chromium-browser http://localhost:8000/$base.html > /dev/null &

#echo "Watching *.adoc for changes"
#inotifywait -m -e close_write *.adoc |
#while read events; do
#  echo $events
#  bundle exec asciidoctor-revealjs $SRCFILE
#done

done

if test -d build; then rm -rf build; fi
mkdir build
cp -r css fonts images videos build
mv *.html build
cd build && ln -s ../reveal.js
#git clone -b 3.9.2 --depth 1 https://github.com/hakimel/reveal.js.git build/reveal.js