#!/bin/bash
#
# Inital Setup see:
#    https://asciidoctor.org/docs/asciidoctor-revealjs/

#SRCFILES=(ch1-poisson.adoc ch2-prog.adoc ch3-diffusion.adoc ch4-elasticite.adoc ch5-stokes.adoc index.adoc)
#for SRCFILE in "${SRCFILES[@]}"; do
for SRCFILE in *.adoc; do

echo "Rendering $SRCFILE"

bundle2.7 exec asciidoctor-revealjs -r asciidoctor-diagram  -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@3.9.2  $SRCFILE
base=`basename $SRCFILE .adoc`
#echo "Starting Webserver on :8000"
#python -m SimpleHTTPServer >/dev/null 2>&1 & 

#chromium-browser http://localhost:8000/$base.html > /dev/null &

#echo "Watching *.adoc for changes"
#inotifywait -m -e close_write *.adoc |
#while read events; do
#  echo $events
#  bundle exec asciidoctor-revealjs $SRCFILE
#done

done

if [! -d build ]; then mkdir build; fi
cp *.html build