name: CI

on: [push]

jobs:

  build_docs:
    runs-on: self-ruby
    name: Build, Install, Package slides
#    if: "!contains(github.event.head_commit.message, 'docs skip')"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'hakimel/reveal.js.git'
        fetch-depth: 1
        ref: '3.9.2'

    - name: Install credentials
      run: echo https://$GITHUB_OAUTH:@github.com > $HOME/.git-credentials
      env:
        GITHUB_OAUTH: ${{ secrets.DOCS_GITHUB_KEY }}
    - name: Build
      run: |
        bundle install --path vendor/bundle   
        ./render bundle
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          # target-folder: ${GITHUB_REF##*/}
          folder: build # The folder the action should deploy.
